name: Pull Request
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      
      - name: Setup Poetry
        uses: snok/install-poetry@v1.1.6
      
      - name: Install Dependencies
        run: poetry install
      
      - name: Flake8
        run: python -m flake8
      
      - name: Isort
        run: python -m isort -c .
      
      - name: Black
        run: python -m black --check .
